Changed split() argument to bytes literal.
This mutates the nine errors to:

======================================================================
ERROR: testCopyToProto_AllExtensions
(google.protobuf.internal.descriptor_test.DescriptorCopyToProtoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File
"protobuf-python3/python/google/protobuf/internal/descriptor_test.py",
line 248, in testCopyToProto_AllExtensions
    TEST_EMPTY_MESSAGE_WITH_EXTENSIONS_ASCII)
  File
"protobuf-python3/python/google/protobuf/internal/descriptor_test.py",
line 154, in _InternalTestCopyToProto
    actual, expected_proto_class, expected_proto_ascii)
  File
"protobuf-python3/python/google/protobuf/internal/descriptor_test.py",
line 142, in _AssertProtoEqual
    text_format.Merge(expected_ascii, expected_proto)
  File
"protobuf-python3/python/google/protobuf/text_format.py",
line 155, in Merge
    tokenizer = _Tokenizer(text)
  File
"protobuf-python3/python/google/protobuf/text_format.py",
line 343, in __init__
    self._lines = deque(text_message.split('\n'))
TypeError: Type str doesn't support the buffer API